project_id = "nekswrhqiqzsqlwbsups"

[functions.analisis-discrepancias]
verify_jwt = false
wall_clock_timeout = 300

[functions.fix-discrepancia-sf]
verify_jwt = false

[functions.check-consistencia-sf]
verify_jwt = false

[functions.check-escritura-antecedente]
verify_jwt = false
