// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nekswrhqiqzsqlwbsups.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5la3N3cmhxaXF6c3Fsd2JzdXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDA1ODMsImV4cCI6MjA1NzM3NjU4M30.1L7hhpE_VHLO4dkyoLaza7JOiMpMsqZYIeGMLqCCIps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});